version: '3'
services:
    jupyterlab:
        build: .
        ports:
        - "8888:8888"
        volumes:
        - "Location to location on host machine :/root"
        restart: always
	container_name: jupyterlab
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
        - "5432:5432"
        volumes:
        - "Volume to map postgres on host machine:/var/lib/postgresql/data"
        environment:
        - "POSTGRES_USER=root"
        - "POSTGRES_PASSWORD=change_me"
        - "POSTGRES_DB=init_database"
