version: '3'
services:
    jupyterlab:
        build: .
        ports:
        - "8888:8888"
        volumes:
        - "location on host machine:/root"
        restart: always
        container_name: jupyterlab
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        ports:
        - "5432:5432"
        volumes:
        - "location on host machine:/var/lib/postgresql/data"
        environment:
        - "POSTGRES_USER=root"
        - "POSTGRES_PASSWORD=change_me"
        - "POSTGRES_DB=init_database"
